apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-lab01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:2023-stable
          ports:
            - containerPort: 80