apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-lab02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-demo
  template:
    metadata:
      labels:
        app: resource-demo
    spec:
      containers:
        - name: demo-container
          image: nginx:latest
          resources:
            limits:
              memory: "2Mi"
              cpu: "200m"