apiVersion: batch/v1
kind: Job
metadata:
  name: automation-processor-lab04
spec:
  template:
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "echo 'Your automation job has successfully complete.'; date"
      restartPolicy: OnFailure
